import fc from "fast-check";
import { describe, expect, it } from "vitest";
import { pbtConfig } from "@/test/pbt";

import {
  hasPermission,
  meetsRoleRequirement,
  type Permission,
  ROLE_PERMISSIONS,
  type Role,
} from "./rbac";

/**
 * RBAC enforcement property tests — Task 4.3
 * ------------------------------------------
 * Property 6 (RBAC Enforcement Consistency), validated at the pure-logic
 * layer that every `withAuth` / `requirePermission` decision is built on.
 *
 * The authorization decision reduces to two total functions:
 *   - `hasPermission(role, permission)` — the allow/deny check
 *   - `meetsRoleRequirement(userRole, requiredRole)` — the role hierarchy
 *
 * These properties exhaustively exercise the full role × permission matrix
 * (generated by fast-check from the real type domains) so that the
 * higher-order enforcement is provably correct for *every* combination,
 * not just the hand-picked examples in `rbac.test.ts`.
 *
 * **Validates: Requirements 4.1, 4.2, 4.3**
 */

// The real domains, drawn from the `Role` and `Permission` type unions. Typed
// annotations make the compiler reject any entry that is not a valid member,
// keeping these lists honest against the source of truth in `rbac.ts`.
const ALL_ROLES: Role[] = ["owner", "admin", "staff", "super_admin"];

const ALL_PERMISSIONS: Permission[] = [
  "tenant:manage",
  "property:write",
  "room:write",
  "resident:write",
  "contract:write",
  "invoice:write",
  "payment:verify",
  "settings:write",
  "team:manage",
  "report:read",
  "subscription:manage",
  "admin:impersonate",
  "admin:suspend",
];

/**
 * The role hierarchy as documented in `meetsRoleRequirement`:
 * staff < admin < owner < super_admin. Used to derive the EXPECTED hierarchy
 * decision independently of the implementation (the test computes the answer
 * a different way than the code under test).
 */
const ROLE_RANK: Record<Role, number> = {
  staff: 0,
  admin: 1,
  owner: 2,
  super_admin: 3,
};

const roleArb = fc.constantFrom(...ALL_ROLES);
const permissionArb = fc.constantFrom(...ALL_PERMISSIONS);

describe("Property 6: RBAC enforcement consistency (Req 4.1, 4.2, 4.3)", () => {
  it("hasPermission(role, p) is true IFF p is in ROLE_PERMISSIONS[role]", () => {
    // **Validates: Requirements 4.1, 4.2, 4.3**
    // Total, exhaustive correctness over the full role × permission matrix:
    // a permission is granted exactly when it appears in the role's set, and
    // denied otherwise. This is the core allow/deny guarantee every
    // `withAuth({ requiredPermission })` decision depends on.
    fc.assert(
      fc.property(roleArb, permissionArb, (role, permission) => {
        const granted = ROLE_PERMISSIONS[role].includes(permission);
        expect(hasPermission(role, permission)).toBe(granted);
      }),
      pbtConfig,
    );
  });

  it("meetsRoleRequirement is monotonic over staff < admin < owner < super_admin", () => {
    // **Validates: Requirements 4.1, 4.2, 4.3**
    // For every ordered pair of roles, a higher-or-equal role always satisfies
    // a lower-or-equal requirement, and a strictly lower role never satisfies a
    // higher requirement. The expected answer is derived from ROLE_RANK, which
    // is computed independently of the implementation's internal hierarchy.
    fc.assert(
      fc.property(roleArb, roleArb, (userRole, requiredRole) => {
        const expected = ROLE_RANK[userRole] >= ROLE_RANK[requiredRole];
        expect(meetsRoleRequirement(userRole, requiredRole)).toBe(expected);
      }),
      pbtConfig,
    );
  });

  it("a role that meets another's requirement holds all of that role's permissions", () => {
    // **Validates: Requirements 4.1, 4.2, 4.3**
    // Cumulative-inheritance coupling: ROLE_PERMISSIONS models a strict
    // superset chain along the hierarchy (staff ⊆ admin ⊆ owner ⊆ super_admin),
    // so whenever `userRole` outranks-or-equals `otherRole`, every permission
    // granted to `otherRole` must also be granted to `userRole`. This ties the
    // hierarchy check to the permission check so the two can never disagree.
    fc.assert(
      fc.property(roleArb, roleArb, (userRole, otherRole) => {
        if (meetsRoleRequirement(userRole, otherRole)) {
          for (const permission of ROLE_PERMISSIONS[otherRole]) {
            expect(hasPermission(userRole, permission)).toBe(true);
          }
        }
      }),
      pbtConfig,
    );
  });
});
